// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#ifdef __cplusplus
#include <cstdbool>
#include <cstdint>
extern "C" {
#else
#include <stdbool.h>
#include <stdint.h>
#endif
#include "objectbox.h"

/// Initializes an ObjectBox model for all entities. 
/// The returned pointer may be NULL if the allocation failed. If the returned model is not NULL, you should check if   
/// any error occurred by calling obx_model_error_code() and/or obx_model_error_message(). If an error occurred, you're
/// responsible for freeing the resources by calling obx_model_free().
/// In case there was no error when setting the model up (i.e. obx_model_error_code() returned 0), you may configure 
/// OBX_store_options with the model by calling obx_opt_model() and subsequently opening a store with obx_store_open().
/// As soon as you call obx_store_open(), the model pointer is consumed and MUST NOT be freed manually.
static inline OBX_model* create_obx_model() {
    OBX_model* model = obx_model();
    if (!model) return NULL;
    
    obx_model_entity(model, "BlockEntity", 1, 57696275262855442);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 5129209301906471667);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "blockId", OBXPropertyType_String, 2, 1199028528895614597);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 1, 4763249224591858941);
    obx_model_property(model, "versionMajor", OBXPropertyType_Short, 3, 6378191700952406938);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "versionMinor", OBXPropertyType_Short, 4, 6088998160400943153);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "projectId", OBXPropertyType_Relation, 5, 8639656024871629269);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ProjectEntity", 2, 1565648307754507732);
    obx_model_property(model, "languageId", OBXPropertyType_Relation, 6, 2434778347853448205);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "LanguageEntity", 3, 7460275118957472292);
    obx_model_property(model, "stateId", OBXPropertyType_Relation, 7, 3690365578827182387);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "StateEntity", 4, 6549930675967498849);
    obx_model_property(model, "type", OBXPropertyType_Byte, 8, 710772247541273247);
    obx_model_property(model, "templateContent", OBXPropertyType_String, 9, 5493023944047535107);
    obx_model_property(model, "defaultsJson", OBXPropertyType_String, 10, 1529399784459475819);
    obx_model_property(model, "description", OBXPropertyType_String, 11, 7006666799014364540);
    obx_model_property(model, "createdAt", OBXPropertyType_Long, 12, 2260519897151071907);
    obx_model_relation(model, 1, 4152549937199351367, 6, 6567933563396494517);
    obx_model_entity_last_property_id(model, 12, 2260519897151071907);
    
    obx_model_entity(model, "CompositionEntity", 2, 562660884330953739);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 5660884704371419291);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "compositionId", OBXPropertyType_String, 2, 1946514701755130748);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 5, 7430145506313043761);
    obx_model_property(model, "projectId", OBXPropertyType_Relation, 3, 8621404584576469278);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ProjectEntity", 6, 48669320816730418);
    obx_model_property(model, "stateId", OBXPropertyType_Relation, 4, 4986598774873823977);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "StateEntity", 7, 1683115489585852495);
    obx_model_property(model, "versionMajor", OBXPropertyType_Short, 5, 7480635436511109680);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "versionMinor", OBXPropertyType_Short, 6, 8945235438308624970);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "fragmentsJson", OBXPropertyType_String, 7, 9180825021972329338);
    obx_model_property(model, "styleProfileJson", OBXPropertyType_String, 8, 5339886255792571264);
    obx_model_property(model, "description", OBXPropertyType_String, 9, 3077709303520992902);
    obx_model_entity_last_property_id(model, 9, 3077709303520992902);
    
    obx_model_entity(model, "LanguageEntity", 3, 1670866351301645916);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 1464835562993684192);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "code", OBXPropertyType_String, 2, 2058815083417228274);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH | OBXPropertyFlags_UNIQUE);
    obx_model_property_index_id(model, 8, 9177139226684487548);
    obx_model_property(model, "nativeName", OBXPropertyType_String, 3, 6475080613085833455);
    obx_model_entity_last_property_id(model, 3, 6475080613085833455);
    
    obx_model_entity(model, "ProjectEntity", 4, 8685612070040541327);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 7083881087941045881);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "key", OBXPropertyType_String, 2, 5290490195030045589);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH | OBXPropertyFlags_UNIQUE);
    obx_model_property_index_id(model, 9, 9117311454775834578);
    obx_model_property(model, "name", OBXPropertyType_String, 3, 939047193770584783);
    obx_model_property(model, "description", OBXPropertyType_String, 4, 6412226719425125879);
    obx_model_entity_last_property_id(model, 4, 6412226719425125879);
    
    obx_model_entity(model, "StateEntity", 5, 7141636622366486680);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 2580277125467523868);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "code", OBXPropertyType_Byte, 2, 263083942621547346);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_UNIQUE);
    obx_model_property_index_id(model, 10, 8575883218779526662);
    obx_model_property(model, "name", OBXPropertyType_String, 3, 7726902316407310215);
    obx_model_property(model, "description", OBXPropertyType_String, 4, 6997458095052701099);
    obx_model_property(model, "isEditable", OBXPropertyType_Bool, 5, 1822056721947058508);
    obx_model_property(model, "color", OBXPropertyType_String, 6, 5835631912848117159);
    obx_model_entity_last_property_id(model, 6, 5835631912848117159);
    
    obx_model_entity(model, "TagEntity", 6, 6567933563396494517);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 2658408236495469980);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "projectId", OBXPropertyType_Relation, 2, 6654261449488996665);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ProjectEntity", 11, 6747301825833540773);
    obx_model_property(model, "name", OBXPropertyType_String, 3, 859662067492348996);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 12, 6654236401403711538);
    obx_model_property(model, "color", OBXPropertyType_String, 4, 278016263539548694);
    obx_model_entity_last_property_id(model, 4, 278016263539548694);
    
    obx_model_entity(model, "AuditLog", 7, 6295336110175675990);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 5707371769760702664);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "createdAt", OBXPropertyType_Date, 2, 9023355124982378391);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "entityType", OBXPropertyType_String, 3, 8551977958270958203);
    obx_model_property(model, "entityId", OBXPropertyType_Long, 4, 8468807059358032720);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "operation", OBXPropertyType_String, 5, 3839215414566226863);
    obx_model_property(model, "userId", OBXPropertyType_String, 6, 3936966133046135632);
    obx_model_property(model, "detailsJson", OBXPropertyType_String, 7, 7546050729990779752);
    obx_model_entity_last_property_id(model, 7, 7546050729990779752);
    
    obx_model_entity(model, "Block", 8, 4943001428679981823);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 1870990730266785750);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "blockId", OBXPropertyType_String, 2, 8303863013635122987);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 13, 530992364187691733);
    obx_model_property(model, "versionMajor", OBXPropertyType_Short, 3, 2166608998529116609);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "versionMinor", OBXPropertyType_Short, 4, 4831900078544148498);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "projectId", OBXPropertyType_Relation, 5, 5073234489106142605);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "Project", 14, 3045982246307612868);
    obx_model_property(model, "languageId", OBXPropertyType_Relation, 6, 8413447917223290972);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "Language", 15, 5356536588763857837);
    obx_model_property(model, "stateId", OBXPropertyType_Relation, 7, 1030786713039587387);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "State", 16, 8426760129687927915);
    obx_model_property(model, "type", OBXPropertyType_Byte, 8, 5096469238783885677);
    obx_model_property(model, "templateContent", OBXPropertyType_String, 9, 617099536593896548);
    obx_model_property(model, "defaultsJson", OBXPropertyType_String, 10, 1202474511629967151);
    obx_model_property(model, "description", OBXPropertyType_String, 11, 6763130479013345836);
    obx_model_property(model, "createdAt", OBXPropertyType_Date, 12, 5408496264368475757);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "updatedAt", OBXPropertyType_Date, 13, 3568948129195108609);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "previousVersionId", OBXPropertyType_Relation, 14, 5147990913340940705);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "Block", 17, 2375341842057500771);
    obx_model_property(model, "nextVersionId", OBXPropertyType_Relation, 15, 3501614420884521353);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "Block", 18, 3100998111389067410);
    obx_model_relation(model, 2, 1681958216555504991, 16, 1188910124985028287);
    obx_model_entity_last_property_id(model, 15, 3501614420884521353);
    
    obx_model_entity(model, "BlockParam", 9, 5570103557602683028);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 8984412954921982222);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "blockId", OBXPropertyType_Relation, 2, 8142396565729070210);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "Block", 19, 6753600746862329712);
    obx_model_property(model, "name", OBXPropertyType_String, 3, 8275885050042173275);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 20, 7656475668756938282);
    obx_model_property(model, "required", OBXPropertyType_Bool, 4, 6254126383890466316);
    obx_model_property(model, "defaultValue", OBXPropertyType_String, 5, 8375414384866664373);
    obx_model_entity_last_property_id(model, 5, 8375414384866664373);
    
    obx_model_entity(model, "BlockUsage", 10, 7262655583489592780);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 8599080108028658539);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "blockId", OBXPropertyType_Relation, 2, 4574066416511166029);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "Block", 21, 4258053881467005621);
    obx_model_property(model, "usageCount", OBXPropertyType_Long, 3, 3779844295925201532);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "lastUsedAt", OBXPropertyType_Date, 4, 1863239407284993978);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "compositionIdsJson", OBXPropertyType_String, 5, 7680491739973784940);
    obx_model_entity_last_property_id(model, 5, 7680491739973784940);
    
    obx_model_entity(model, "Composition", 11, 6114696665850993207);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 3814356238973095714);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "compositionId", OBXPropertyType_String, 2, 3480184400528201495);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 22, 812020512002916839);
    obx_model_property(model, "projectId", OBXPropertyType_Relation, 3, 4797438095773333562);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "Project", 23, 6850129915895586064);
    obx_model_property(model, "stateId", OBXPropertyType_Relation, 4, 6924506854953449170);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "State", 24, 682753437743707749);
    obx_model_property(model, "versionMajor", OBXPropertyType_Short, 5, 6342944438326742972);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "versionMinor", OBXPropertyType_Short, 6, 5050856274807411139);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "targetLanguageId", OBXPropertyType_Relation, 7, 8801658036662946341);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "Language", 25, 8377713999315452729);
    obx_model_property(model, "structuralStyleJson", OBXPropertyType_String, 8, 5448587404191117976);
    obx_model_property(model, "semanticStyleJson", OBXPropertyType_String, 9, 3756222673954986126);
    obx_model_property(model, "description", OBXPropertyType_String, 10, 8904244876773985088);
    obx_model_property(model, "createdAt", OBXPropertyType_Date, 11, 194682182273150674);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "updatedAt", OBXPropertyType_Date, 12, 589806453329240809);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "previousVersionId", OBXPropertyType_Relation, 13, 2796363176682541580);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "Composition", 26, 592707911850055032);
    obx_model_property(model, "nextVersionId", OBXPropertyType_Relation, 14, 9029452982129102374);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "Composition", 27, 2303185552553673995);
    obx_model_entity_last_property_id(model, 14, 9029452982129102374);
    
    obx_model_entity(model, "Fragment", 12, 4152522461539627863);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 9051432534103074534);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "compositionId", OBXPropertyType_Relation, 2, 7120714838731852010);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "Composition", 28, 2439507049812817751);
    obx_model_property(model, "orderIndex", OBXPropertyType_Int, 3, 4972041658278003259);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_UNSIGNED);
    obx_model_property_index_id(model, 29, 5192330739611001596);
    obx_model_property(model, "fragmentType", OBXPropertyType_Byte, 4, 8454737284448586891);
    obx_model_property(model, "refBlockId", OBXPropertyType_String, 5, 7515779558467346916);
    obx_model_property(model, "refVersionMajor", OBXPropertyType_Short, 6, 4526026091314638494);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "refVersionMinor", OBXPropertyType_Short, 7, 3191789880515503675);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "refUseLatest", OBXPropertyType_Bool, 8, 8863034920697582422);
    obx_model_property(model, "refLocalParamsJson", OBXPropertyType_String, 9, 3093106176464569848);
    obx_model_property(model, "staticContent", OBXPropertyType_String, 10, 4490735054290718);
    obx_model_property(model, "separatorType", OBXPropertyType_Byte, 11, 8191586964666734619);
    obx_model_entity_last_property_id(model, 11, 8191586964666734619);
    
    obx_model_entity(model, "Language", 13, 5793504984911009669);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 8572074958598361325);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "code", OBXPropertyType_String, 2, 2997829720586255358);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH | OBXPropertyFlags_UNIQUE);
    obx_model_property_index_id(model, 30, 3528553895637913762);
    obx_model_property(model, "nativeName", OBXPropertyType_String, 3, 6365496957627311805);
    obx_model_entity_last_property_id(model, 3, 6365496957627311805);
    
    obx_model_entity(model, "Project", 14, 6101437057925707805);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 12642157649163685);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "key", OBXPropertyType_String, 2, 4879268997700539446);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH | OBXPropertyFlags_UNIQUE);
    obx_model_property_index_id(model, 31, 8408189818251469528);
    obx_model_property(model, "name", OBXPropertyType_String, 3, 8084976570353636422);
    obx_model_property(model, "description", OBXPropertyType_String, 4, 5815701098508186499);
    obx_model_property(model, "createdAt", OBXPropertyType_Date, 5, 7457785811120544802);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "updatedAt", OBXPropertyType_Date, 6, 2195413757460513120);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_entity_last_property_id(model, 6, 2195413757460513120);
    
    obx_model_entity(model, "State", 15, 787972814753526170);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 4190736361543997485);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "code", OBXPropertyType_Byte, 2, 3521864640388833515);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_UNIQUE);
    obx_model_property_index_id(model, 32, 8677812826052010820);
    obx_model_property(model, "name", OBXPropertyType_String, 3, 7190170368525339818);
    obx_model_property(model, "description", OBXPropertyType_String, 4, 4543969917487505937);
    obx_model_entity_last_property_id(model, 4, 4543969917487505937);
    
    obx_model_entity(model, "Tag", 16, 1188910124985028287);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 805018694657059763);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "projectId", OBXPropertyType_Relation, 2, 5151124271278084430);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "Project", 33, 1769371075400577988);
    obx_model_property(model, "name", OBXPropertyType_String, 3, 4424390433173747288);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 34, 8785835493740944091);
    obx_model_property(model, "createdAt", OBXPropertyType_Date, 4, 5449200163072290257);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_entity_last_property_id(model, 4, 5449200163072290257);
    
    obx_model_entity(model, "ObxAuditLog", 17, 8109528970418338120);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 4463830278217255861);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "createdAt", OBXPropertyType_Date, 2, 3687739152273630979);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "entityType", OBXPropertyType_String, 3, 4090746717551909987);
    obx_model_property(model, "entityId", OBXPropertyType_Long, 4, 6741866457312085371);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "operation", OBXPropertyType_String, 5, 2597004069734179195);
    obx_model_property(model, "userId", OBXPropertyType_String, 6, 358559562285609240);
    obx_model_property(model, "detailsJson", OBXPropertyType_String, 7, 8472594470331430384);
    obx_model_entity_last_property_id(model, 7, 8472594470331430384);
    
    obx_model_entity(model, "ObxBlock", 18, 4229572312024629952);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 1716521843343506613);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "blockId", OBXPropertyType_String, 2, 5645237428785535960);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 35, 2829578497216503651);
    obx_model_property(model, "versionMajor", OBXPropertyType_Short, 3, 5593769109490680329);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "versionMinor", OBXPropertyType_Short, 4, 1518883151809832006);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "projectId", OBXPropertyType_Relation, 5, 457558560494136900);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxProject", 36, 8684439689311352741);
    obx_model_property(model, "languageId", OBXPropertyType_Relation, 6, 8572639939029251689);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxLanguage", 37, 8821119637825524803);
    obx_model_property(model, "stateId", OBXPropertyType_Relation, 7, 3229680073772549911);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxState", 38, 4867770292206682001);
    obx_model_property(model, "type", OBXPropertyType_Byte, 8, 3781743197529634023);
    obx_model_property(model, "templateContent", OBXPropertyType_String, 9, 5748271900735229135);
    obx_model_property(model, "defaultsJson", OBXPropertyType_String, 10, 1710873459636100629);
    obx_model_property(model, "description", OBXPropertyType_String, 11, 5573069865148944233);
    obx_model_property(model, "createdAt", OBXPropertyType_Date, 12, 3363375049567830844);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "updatedAt", OBXPropertyType_Date, 13, 7631057877081221464);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "previousVersionId", OBXPropertyType_Relation, 14, 8403231824201927016);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxBlock", 39, 8213146442075310323);
    obx_model_property(model, "nextVersionId", OBXPropertyType_Relation, 15, 4276232648218145728);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxBlock", 40, 987736793127681074);
    obx_model_relation(model, 3, 4350534257507534229, 26, 8148437322667548321);
    obx_model_entity_last_property_id(model, 15, 4276232648218145728);
    
    obx_model_entity(model, "ObxBlockParam", 19, 2067758439051960785);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 255281176265107388);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "blockId", OBXPropertyType_Relation, 2, 1403513089045471248);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxBlock", 41, 5244745171809410966);
    obx_model_property(model, "name", OBXPropertyType_String, 3, 6391671757789240170);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 42, 1000288106356521781);
    obx_model_property(model, "required", OBXPropertyType_Bool, 4, 303587734755549318);
    obx_model_property(model, "defaultValue", OBXPropertyType_String, 5, 848666151043165809);
    obx_model_entity_last_property_id(model, 5, 848666151043165809);
    
    obx_model_entity(model, "ObxBlockUsage", 20, 3514173954177295020);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 7982292215244065149);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "blockId", OBXPropertyType_Relation, 2, 6726183029071653270);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxBlock", 43, 8217734895396769669);
    obx_model_property(model, "usageCount", OBXPropertyType_Long, 3, 1578708559579972804);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "lastUsedAt", OBXPropertyType_Date, 4, 4711801221325656786);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "compositionIdsJson", OBXPropertyType_String, 5, 2275721006182547997);
    obx_model_entity_last_property_id(model, 5, 2275721006182547997);
    
    obx_model_entity(model, "ObxComposition", 21, 19642391171978850);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 9121673142957595910);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "compositionId", OBXPropertyType_String, 2, 8461066205001328106);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 44, 2398076529948140058);
    obx_model_property(model, "projectId", OBXPropertyType_Relation, 3, 1439146589622815434);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxProject", 45, 5344904519865127346);
    obx_model_property(model, "stateId", OBXPropertyType_Relation, 4, 1879389637711204020);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxState", 46, 6624866216391166814);
    obx_model_property(model, "versionMajor", OBXPropertyType_Short, 5, 547165990608698712);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "versionMinor", OBXPropertyType_Short, 6, 8830465038029708958);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "targetLanguageId", OBXPropertyType_Relation, 7, 8802632186748715719);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxLanguage", 47, 8473803315401206781);
    obx_model_property(model, "structuralStyleJson", OBXPropertyType_String, 8, 3319164479583285105);
    obx_model_property(model, "semanticStyleJson", OBXPropertyType_String, 9, 4392154557617036342);
    obx_model_property(model, "description", OBXPropertyType_String, 10, 8763757478433694728);
    obx_model_property(model, "createdAt", OBXPropertyType_Date, 11, 7892637950343919427);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "updatedAt", OBXPropertyType_Date, 12, 7266094097183231814);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "previousVersionId", OBXPropertyType_Relation, 13, 5830130573710682391);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxComposition", 48, 6227003334801516872);
    obx_model_property(model, "nextVersionId", OBXPropertyType_Relation, 14, 807517261865152304);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxComposition", 49, 8539442189846529322);
    obx_model_entity_last_property_id(model, 14, 807517261865152304);
    
    obx_model_entity(model, "ObxFragment", 22, 2887310798474797674);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 2374365281596082139);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "compositionId", OBXPropertyType_Relation, 2, 1239912064001796824);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxComposition", 50, 5757771030107314431);
    obx_model_property(model, "orderIndex", OBXPropertyType_Int, 3, 5547278047741586015);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_UNSIGNED);
    obx_model_property_index_id(model, 51, 955033855617170654);
    obx_model_property(model, "fragmentType", OBXPropertyType_Byte, 4, 7992939127314156984);
    obx_model_property(model, "refBlockId", OBXPropertyType_String, 5, 3005768508864797608);
    obx_model_property(model, "refVersionMajor", OBXPropertyType_Short, 6, 3595190640824945038);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "refVersionMinor", OBXPropertyType_Short, 7, 6077381666910822696);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "refUseLatest", OBXPropertyType_Bool, 8, 4062001980603807764);
    obx_model_property(model, "refLocalParamsJson", OBXPropertyType_String, 9, 65023379851634381);
    obx_model_property(model, "staticContent", OBXPropertyType_String, 10, 5585247828834719531);
    obx_model_property(model, "separatorType", OBXPropertyType_Byte, 11, 6788030598517637605);
    obx_model_entity_last_property_id(model, 11, 6788030598517637605);
    
    obx_model_entity(model, "ObxLanguage", 23, 8073167299609748193);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 4742032145132847130);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "code", OBXPropertyType_String, 2, 9167761392010296268);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH | OBXPropertyFlags_UNIQUE);
    obx_model_property_index_id(model, 52, 7358343623602282827);
    obx_model_property(model, "nativeName", OBXPropertyType_String, 3, 301558688515763888);
    obx_model_entity_last_property_id(model, 3, 301558688515763888);
    
    obx_model_entity(model, "ObxProject", 24, 6071961163271335937);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 595992226973802841);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "key", OBXPropertyType_String, 2, 1857338850379635814);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH | OBXPropertyFlags_UNIQUE);
    obx_model_property_index_id(model, 53, 6097387086030939612);
    obx_model_property(model, "name", OBXPropertyType_String, 3, 1094329648148203529);
    obx_model_property(model, "description", OBXPropertyType_String, 4, 158232277970529326);
    obx_model_property(model, "createdAt", OBXPropertyType_Date, 5, 2893819131807305121);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "updatedAt", OBXPropertyType_Date, 6, 4620267012567901785);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_entity_last_property_id(model, 6, 4620267012567901785);
    
    obx_model_entity(model, "ObxState", 25, 7268592802200342439);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 8535034296460678552);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "code", OBXPropertyType_Byte, 2, 1225734298014231969);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_UNIQUE);
    obx_model_property_index_id(model, 54, 7843103340756117273);
    obx_model_property(model, "name", OBXPropertyType_String, 3, 6976458048676111202);
    obx_model_property(model, "description", OBXPropertyType_String, 4, 538706536824680114);
    obx_model_entity_last_property_id(model, 4, 538706536824680114);
    
    obx_model_entity(model, "ObxTag", 26, 8148437322667548321);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 6176723263153724649);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "projectId", OBXPropertyType_Relation, 2, 2152405014218236510);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxProject", 55, 7841572014731479029);
    obx_model_property(model, "name", OBXPropertyType_String, 3, 2236408651111043544);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 56, 8322369737688442627);
    obx_model_property(model, "createdAt", OBXPropertyType_Date, 4, 8411617566963567872);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_entity_last_property_id(model, 4, 8411617566963567872);
    
    obx_model_last_entity_id(model, 26, 8148437322667548321);
    obx_model_last_index_id(model, 56, 8322369737688442627);
    obx_model_last_relation_id(model, 3, 4350534257507534229);
    return model; // NOTE: the returned model will contain error information if an error occurred.
}

#ifdef __cplusplus
}
#endif
