// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#ifdef __cplusplus
#include <cstdbool>
#include <cstdint>
extern "C" {
#else
#include <stdbool.h>
#include <stdint.h>
#endif
#include "objectbox.h"

/// Initializes an ObjectBox model for all entities. 
/// The returned pointer may be NULL if the allocation failed. If the returned model is not NULL, you should check if   
/// any error occurred by calling obx_model_error_code() and/or obx_model_error_message(). If an error occurred, you're
/// responsible for freeing the resources by calling obx_model_free().
/// In case there was no error when setting the model up (i.e. obx_model_error_code() returned 0), you may configure 
/// OBX_store_options with the model by calling obx_opt_model() and subsequently opening a store with obx_store_open().
/// As soon as you call obx_store_open(), the model pointer is consumed and MUST NOT be freed manually.
static inline OBX_model* create_obx_model() {
    OBX_model* model = obx_model();
    if (!model) return NULL;
    
    obx_model_entity(model, "ObxAuditLog", 1, 3486556126890379663);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 2214554370488076382);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "createdAt", OBXPropertyType_Date, 2, 3506239280332526389);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "entityType", OBXPropertyType_String, 3, 4482760038498926548);
    obx_model_property(model, "entityId", OBXPropertyType_Long, 4, 3988205158127297815);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "operation", OBXPropertyType_String, 5, 2789092730318726264);
    obx_model_property(model, "userId", OBXPropertyType_String, 6, 1723724515437558887);
    obx_model_property(model, "detailsJson", OBXPropertyType_String, 7, 6382725116332418668);
    obx_model_entity_last_property_id(model, 7, 6382725116332418668);
    
    obx_model_entity(model, "ObxBlock", 2, 2419412424179453468);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 332737791752134479);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "blockId", OBXPropertyType_String, 2, 873629523902239538);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 1, 6776742879252443622);
    obx_model_property(model, "versionMajor", OBXPropertyType_Short, 3, 1043641358241571982);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "versionMinor", OBXPropertyType_Short, 4, 4944382978999545762);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "projectId", OBXPropertyType_Relation, 5, 6964255108966420280);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxProject", 2, 6201078563201984979);
    obx_model_property(model, "languageId", OBXPropertyType_Relation, 6, 912344703733303434);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxLanguage", 3, 1137865073665502452);
    obx_model_property(model, "state", OBXPropertyType_Byte, 7, 1066852842988807085);
    obx_model_property(model, "type", OBXPropertyType_Byte, 8, 5993588606601763012);
    obx_model_property(model, "templateContent", OBXPropertyType_String, 9, 1955988582939614146);
    obx_model_property(model, "defaultsJson", OBXPropertyType_String, 10, 4142586662763137350);
    obx_model_property(model, "paramsJson", OBXPropertyType_String, 11, 2084984020101507384);
    obx_model_property(model, "description", OBXPropertyType_String, 12, 3440974925327366262);
    obx_model_property(model, "createdAt", OBXPropertyType_Long, 13, 1047850774962802466);
    obx_model_property(model, "updatedAt", OBXPropertyType_Long, 14, 5488124296738568161);
    obx_model_property(model, "previousVersionId", OBXPropertyType_Relation, 15, 2477372764567074401);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxBlock", 4, 2710185122806534609);
    obx_model_property(model, "nextVersionId", OBXPropertyType_Relation, 16, 6101633986158951426);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxBlock", 5, 8368360337530499642);
    obx_model_relation(model, 1, 1369909837411946385, 8, 7488814803516279037);
    obx_model_entity_last_property_id(model, 16, 6101633986158951426);
    
    obx_model_entity(model, "ObxBlockUsage", 3, 5545948432654789716);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 3861123283439100209);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "blockId", OBXPropertyType_Relation, 2, 3406028565571673254);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxBlock", 6, 697211012772602908);
    obx_model_property(model, "usageCount", OBXPropertyType_Long, 3, 9035683715649156196);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "lastUsedAt", OBXPropertyType_Long, 4, 9075234929563453921);
    obx_model_property(model, "compositionIdsJson", OBXPropertyType_String, 5, 9067083493629389318);
    obx_model_entity_last_property_id(model, 5, 9067083493629389318);
    
    obx_model_entity(model, "ObxComposition", 4, 1885837618698523194);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 9037253685589007890);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "compositionId", OBXPropertyType_String, 2, 3584318749876422359);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 7, 2917882431520203654);
    obx_model_property(model, "projectId", OBXPropertyType_Relation, 3, 1909216451171546311);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxProject", 8, 7590914006066435128);
    obx_model_property(model, "state", OBXPropertyType_Byte, 4, 1857890882368816099);
    obx_model_property(model, "versionMajor", OBXPropertyType_Short, 5, 3424346275741822669);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "versionMinor", OBXPropertyType_Short, 6, 5468302990891741748);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "targetLanguageId", OBXPropertyType_Relation, 7, 1375010210826627039);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxLanguage", 9, 3357579991842696158);
    obx_model_property(model, "description", OBXPropertyType_String, 10, 5803675816883414304);
    obx_model_property(model, "createdAt", OBXPropertyType_Long, 11, 7930516982725304848);
    obx_model_property(model, "updatedAt", OBXPropertyType_Long, 12, 4128778362145994394);
    obx_model_property(model, "previousVersionId", OBXPropertyType_Relation, 13, 7776332083356539323);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxComposition", 10, 4843881958623149956);
    obx_model_property(model, "nextVersionId", OBXPropertyType_Relation, 14, 5784495734909918495);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxComposition", 11, 8927559632122075829);
    obx_model_property(model, "styleProfileJson", OBXPropertyType_String, 15, 2713886912131433208);
    obx_model_entity_last_property_id(model, 15, 2713886912131433208);
    
    obx_model_entity(model, "ObxFragment", 5, 515850691231794682);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 3499244162769012114);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "compositionId", OBXPropertyType_Relation, 2, 5209857666512837518);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxComposition", 12, 3343628311672821989);
    obx_model_property(model, "orderIndex", OBXPropertyType_Int, 3, 8213526494309275814);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_UNSIGNED);
    obx_model_property_index_id(model, 13, 9015908064021938569);
    obx_model_property(model, "fragmentType", OBXPropertyType_Byte, 4, 4789389256925146821);
    obx_model_property(model, "refBlockId", OBXPropertyType_String, 5, 3958286833178169469);
    obx_model_property(model, "refVersionMajor", OBXPropertyType_Short, 6, 201026427630881145);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "refVersionMinor", OBXPropertyType_Short, 7, 2845049687682960741);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "refUseLatest", OBXPropertyType_Bool, 8, 1773029901654945127);
    obx_model_property(model, "refLocalParamsJson", OBXPropertyType_String, 9, 4383263765440131768);
    obx_model_property(model, "staticContent", OBXPropertyType_String, 10, 5952987180705548697);
    obx_model_property(model, "separatorType", OBXPropertyType_Byte, 11, 105249975285181746);
    obx_model_entity_last_property_id(model, 11, 105249975285181746);
    
    obx_model_entity(model, "ObxLanguage", 6, 2407694020417353093);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 675362085673889402);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "code", OBXPropertyType_String, 2, 7895223631615969861);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH | OBXPropertyFlags_UNIQUE);
    obx_model_property_index_id(model, 14, 3839464032562610522);
    obx_model_property(model, "nativeName", OBXPropertyType_String, 3, 2486737883398218738);
    obx_model_entity_last_property_id(model, 3, 2486737883398218738);
    
    obx_model_entity(model, "ObxProject", 7, 3155233238031422165);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 5533930488139096011);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "key", OBXPropertyType_String, 2, 8816063985851179648);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH | OBXPropertyFlags_UNIQUE);
    obx_model_property_index_id(model, 15, 5707610885390312033);
    obx_model_property(model, "name", OBXPropertyType_String, 3, 4526502123023764784);
    obx_model_property(model, "description", OBXPropertyType_String, 4, 4005295130969598528);
    obx_model_property(model, "createdAt", OBXPropertyType_Long, 5, 9020587438181644941);
    obx_model_property(model, "updatedAt", OBXPropertyType_Long, 6, 4741011244673191319);
    obx_model_entity_last_property_id(model, 6, 4741011244673191319);
    
    obx_model_entity(model, "ObxTag", 8, 7488814803516279037);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 2108250320641201970);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "projectId", OBXPropertyType_Relation, 2, 1709407488256840161);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxProject", 16, 5160747330705811946);
    obx_model_property(model, "name", OBXPropertyType_String, 3, 8215223810342296155);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 17, 1234544260600394781);
    obx_model_property(model, "createdAt", OBXPropertyType_Date, 4, 4636538930359369580);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_entity_last_property_id(model, 4, 4636538930359369580);
    
    obx_model_last_entity_id(model, 8, 7488814803516279037);
    obx_model_last_index_id(model, 17, 1234544260600394781);
    obx_model_last_relation_id(model, 1, 1369909837411946385);
    return model; // NOTE: the returned model will contain error information if an error occurred.
}

#ifdef __cplusplus
}
#endif
