// Code generated by ObjectBox; DO NOT EDIT.

#pragma once

#ifdef __cplusplus
#include <cstdbool>
#include <cstdint>
extern "C" {
#else
#include <stdbool.h>
#include <stdint.h>
#endif
#include "objectbox.h"

/// Initializes an ObjectBox model for all entities. 
/// The returned pointer may be NULL if the allocation failed. If the returned model is not NULL, you should check if   
/// any error occurred by calling obx_model_error_code() and/or obx_model_error_message(). If an error occurred, you're
/// responsible for freeing the resources by calling obx_model_free().
/// In case there was no error when setting the model up (i.e. obx_model_error_code() returned 0), you may configure 
/// OBX_store_options with the model by calling obx_opt_model() and subsequently opening a store with obx_store_open().
/// As soon as you call obx_store_open(), the model pointer is consumed and MUST NOT be freed manually.
static inline OBX_model* create_obx_model() {
    OBX_model* model = obx_model();
    if (!model) return NULL;
    
    obx_model_entity(model, "ObxAuditLog", 1, 2991683770301629259);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 8024121227667602653);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "createdAt", OBXPropertyType_Date, 2, 7783889174622498754);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_property(model, "entityType", OBXPropertyType_String, 3, 3085393153552418394);
    obx_model_property(model, "entityId", OBXPropertyType_Long, 4, 6487671346544554005);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "operation", OBXPropertyType_String, 5, 7088553745012433650);
    obx_model_property(model, "userId", OBXPropertyType_String, 6, 7494711865581244607);
    obx_model_property(model, "detailsJson", OBXPropertyType_String, 7, 7170024846496000172);
    obx_model_entity_last_property_id(model, 7, 7170024846496000172);
    
    obx_model_entity(model, "ObxBlock", 2, 2463514165070338570);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 4878560266177082350);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "blockId", OBXPropertyType_String, 2, 6780103854138314237);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 1, 4176245265719070425);
    obx_model_property(model, "versionMajor", OBXPropertyType_Short, 3, 2133348522342002848);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "versionMinor", OBXPropertyType_Short, 4, 2994633433506336927);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "projectId", OBXPropertyType_Relation, 5, 4252676753870844850);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxProject", 2, 4959536488809591721);
    obx_model_property(model, "languageId", OBXPropertyType_Relation, 6, 1409576478805522880);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxLanguage", 3, 8625238034767627681);
    obx_model_property(model, "state", OBXPropertyType_Byte, 7, 22175441694912899);
    obx_model_property(model, "type", OBXPropertyType_Byte, 8, 6862992091472031146);
    obx_model_property(model, "templateContent", OBXPropertyType_String, 9, 4933607956089917145);
    obx_model_property(model, "defaultsJson", OBXPropertyType_String, 10, 7666496882764337363);
    obx_model_property(model, "paramsJson", OBXPropertyType_String, 11, 4202413801832075830);
    obx_model_property(model, "description", OBXPropertyType_String, 12, 513575648726411780);
    obx_model_property(model, "createdAt", OBXPropertyType_Long, 13, 7234196366045297628);
    obx_model_property(model, "updatedAt", OBXPropertyType_Long, 14, 9032069874772562826);
    obx_model_property(model, "previousVersionId", OBXPropertyType_Relation, 15, 3807646713430399593);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxBlock", 4, 5190649506948353375);
    obx_model_property(model, "nextVersionId", OBXPropertyType_Relation, 16, 5735441314333160594);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxBlock", 5, 8704321735865194754);
    obx_model_relation(model, 1, 1156941716620325821, 8, 4237023681596028475);
    obx_model_entity_last_property_id(model, 16, 5735441314333160594);
    
    obx_model_entity(model, "ObxBlockUsage", 3, 6547491752945837447);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 3406242324464466702);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "blockId", OBXPropertyType_Relation, 2, 2079516535869673214);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxBlock", 6, 7420276204029565489);
    obx_model_property(model, "usageCount", OBXPropertyType_Long, 3, 7617115507283495644);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "lastUsedAt", OBXPropertyType_Long, 4, 2874360746443009989);
    obx_model_property(model, "compositionIdsJson", OBXPropertyType_String, 5, 8027950834216217356);
    obx_model_entity_last_property_id(model, 5, 8027950834216217356);
    
    obx_model_entity(model, "ObxComposition", 4, 8217696797710853574);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 8568637532292486044);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "compositionId", OBXPropertyType_String, 2, 8825576629818288022);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 7, 2057254206362775364);
    obx_model_property(model, "projectId", OBXPropertyType_Relation, 3, 3540705811250263011);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxProject", 8, 440737591203670208);
    obx_model_property(model, "state", OBXPropertyType_Byte, 4, 4948125490472951658);
    obx_model_property(model, "versionMajor", OBXPropertyType_Short, 5, 8611144092776914643);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "versionMinor", OBXPropertyType_Short, 6, 970989777041305229);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "targetLanguageId", OBXPropertyType_Relation, 7, 5171992485726289923);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxLanguage", 9, 2025254632832273838);
    obx_model_property(model, "styleProfileJson", OBXPropertyType_String, 8, 6690462202323846570);
    obx_model_property(model, "description", OBXPropertyType_String, 9, 4806494140800547245);
    obx_model_property(model, "createdAt", OBXPropertyType_Long, 10, 6183176733831079904);
    obx_model_property(model, "updatedAt", OBXPropertyType_Long, 11, 8301971982425191518);
    obx_model_property(model, "previousVersionId", OBXPropertyType_Relation, 12, 1878763322463289324);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxComposition", 10, 7361577577435781261);
    obx_model_property(model, "nextVersionId", OBXPropertyType_Relation, 13, 6707243730987651195);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxComposition", 11, 2551157760948844263);
    obx_model_entity_last_property_id(model, 13, 6707243730987651195);
    
    obx_model_entity(model, "ObxFragment", 5, 8820645143558886526);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 1604315249504434317);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "compositionId", OBXPropertyType_Relation, 2, 2811774327237687074);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxComposition", 12, 691716353019660070);
    obx_model_property(model, "orderIndex", OBXPropertyType_Int, 3, 8839584405913340812);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_UNSIGNED);
    obx_model_property_index_id(model, 13, 325683685975178973);
    obx_model_property(model, "fragmentType", OBXPropertyType_Byte, 4, 3099775934825134091);
    obx_model_property(model, "refBlockId", OBXPropertyType_String, 5, 6822967522134224931);
    obx_model_property(model, "refVersionMajor", OBXPropertyType_Short, 6, 4842650988396836202);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "refVersionMinor", OBXPropertyType_Short, 7, 5543078172427623092);
    obx_model_property_flags(model, OBXPropertyFlags_UNSIGNED);
    obx_model_property(model, "refUseLatest", OBXPropertyType_Bool, 8, 6856475616396094968);
    obx_model_property(model, "refLocalParamsJson", OBXPropertyType_String, 9, 2800787767691528772);
    obx_model_property(model, "staticContent", OBXPropertyType_String, 10, 6499219811890642134);
    obx_model_property(model, "separatorType", OBXPropertyType_Byte, 11, 2522240140628024477);
    obx_model_entity_last_property_id(model, 11, 2522240140628024477);
    
    obx_model_entity(model, "ObxLanguage", 6, 7756015634814673224);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 5979876230051739082);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "code", OBXPropertyType_String, 2, 3486723589620213582);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH | OBXPropertyFlags_UNIQUE);
    obx_model_property_index_id(model, 14, 279028339613876782);
    obx_model_property(model, "nativeName", OBXPropertyType_String, 3, 3050768014772892597);
    obx_model_entity_last_property_id(model, 3, 3050768014772892597);
    
    obx_model_entity(model, "ObxProject", 7, 4175831137713553291);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 776246038561305877);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "key", OBXPropertyType_String, 2, 2761004578230491607);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH | OBXPropertyFlags_UNIQUE);
    obx_model_property_index_id(model, 15, 6761077077597506491);
    obx_model_property(model, "name", OBXPropertyType_String, 3, 6666051753063474421);
    obx_model_property(model, "description", OBXPropertyType_String, 4, 5849934225033882653);
    obx_model_property(model, "createdAt", OBXPropertyType_Long, 5, 6498924204866124473);
    obx_model_property(model, "updatedAt", OBXPropertyType_Long, 6, 1954539458091203751);
    obx_model_entity_last_property_id(model, 6, 1954539458091203751);
    
    obx_model_entity(model, "ObxTag", 8, 4237023681596028475);
    obx_model_property(model, "id", OBXPropertyType_Long, 1, 3936334558156242380);
    obx_model_property_flags(model, OBXPropertyFlags_ID);
    obx_model_property(model, "projectId", OBXPropertyType_Relation, 2, 9143597388731622328);
    obx_model_property_flags(model, OBXPropertyFlags_INDEXED | OBXPropertyFlags_INDEX_PARTIAL_SKIP_ZERO);
    obx_model_property_relation(model, "ObxProject", 16, 8775711066509932405);
    obx_model_property(model, "name", OBXPropertyType_String, 3, 8060858918251202382);
    obx_model_property_flags(model, OBXPropertyFlags_INDEX_HASH);
    obx_model_property_index_id(model, 17, 6797439816628500550);
    obx_model_property(model, "createdAt", OBXPropertyType_Date, 4, 2241554567507815475);
    obx_model_property_flags(model, OBXPropertyFlags_ID_COMPANION);
    obx_model_entity_last_property_id(model, 4, 2241554567507815475);
    
    obx_model_last_entity_id(model, 8, 4237023681596028475);
    obx_model_last_index_id(model, 17, 6797439816628500550);
    obx_model_last_relation_id(model, 1, 1156941716620325821);
    return model; // NOTE: the returned model will contain error information if an error occurred.
}

#ifdef __cplusplus
}
#endif
